# This is a basic workflow to help you get started with Actions

name: firstTest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: get system date on Ubuntu
        run: date
  build_ms:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: get system date on windows
        run: Get-Date
  
  build_iOS:
    runs-on: macOS-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: get system date on MacOS
        run: date
    
  build_depends:
    needs: [build_ubuntu, build_ms, build_iOS]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: get system date on ubuntu again
        run: date
