# name of the workflow
name: secondChallenge

# Runs on condition

on: 
  push:
    branches: [ main ]

# Name of the artifact
env:
  artifact_name: "ArtifactNameRahul"

jobs:

  job1:
    runs-on: ubuntu-latest

    # Checkout the code to the host system
    steps:
      - name: checkout
        uses: actions/checkout@v2
        #run: echo successfully checked out

      # downloading the artifact
      - name: $artifact_name
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifact_name }}
          path: ./${{ env.artifact_name }}
      
        #run: echo Artifact $artifact_name uploaded.
