# name of the workflow
name: secondChallenge

# Runs on condition

on: 
  push:
    branches: [ main ]

# Name of the artifact
env:
  artifact_name: "ArtifactNameRahul"

jobs:

  job1:
    runs-on: ubuntu-latest

    # Checkout the code to the host system
    steps:
      - uses: actions/checkout@v2
      - name: checkout
        run: echo successfully checked out

      # downloading the artifact
      - name: $artifact_name
      - uses: actions/upload-artifact
        with:
          name: $artifact_name
          path: ./{{ env.artifact_name }}.exe
      
        run: echo Artifact $artifact_name uploaded.
